=== clockard/OpenDJ/opends/tests/system-tests/scenario/conf.dtd
<!--
 ! CDDL HEADER START
 !
 ! The contents of this file are subject to the terms of the
 ! Common Development and Distribution License, Version 1.0 only
 ! (the "License").  You may not use this file except in compliance
 ! with the License.
 !
 ! You can obtain a copy of the license at
 ! trunk/opends/resource/legal-notices/OpenDS.LICENSE
 ! or https://OpenDS.dev.java.net/OpenDS.LICENSE.
 ! See the License for the specific language governing permissions
 ! and limitations under the License.
 !
 ! When distributing Covered Code, include this CDDL HEADER in each
 ! file and include the License file at
 ! trunk/opends/resource/legal-notices/OpenDS.LICENSE.  If applicable,
 ! add the following below this CDDL HEADER, with the fields enclosed
 ! by brackets "[]" replaced with your own identifying information:
 !      Portions Copyright [yyyy] [name of copyright owner]
 !
 ! CDDL HEADER END
 !
 !      Copyright 2008 Sun Microsystems, Inc.
 ! -->

<!ELEMENT systemTestConfiguration (globalParameters, instance+, 
                                   suffix?, scheduler?)>

<!-- ========== GLOBAL PARAMETERS NODE ========================= -->
<!ELEMENT globalParameters (scenario,opendsZip,directoryManagerDn?,
                            directoryManagerPswd?,domain?)>
  <!ELEMENT scenario (name,description)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
  <!ELEMENT opendsZip (#PCDATA)>
  <!ELEMENT directoryManagerDn (#PCDATA)>
  <!ELEMENT directoryManagerPswd (#PCDATA)>
  <!ELEMENT domain (#PCDATA)>

<!-- ========== INSTANCE NODE ========================= -->
<!ELEMENT instance (host,installDir,ports?,security?,tuning?)>
<!ATTLIST instance 
    name NMTOKEN #REQUIRED 
    product NMTOKEN #REQUIRED
    role ( ldapServer | ldapProxy ) "ldapServer">
  
  <!ELEMENT host (#PCDATA)>
  <!ELEMENT installDir (#PCDATA)>
  <!ELEMENT ports (ldap?,ldaps?,jmx?,replicationServer?)>
    <!ELEMENT ldap (#PCDATA)>
    <!ELEMENT ldaps (#PCDATA)>
    <!ELEMENT jmx (#PCDATA)>
    <!ELEMENT replicationServer (#PCDATA)>
  <!ELEMENT security EMPTY>
  <!ATTLIST security
        sslEnabled ( true | false ) "false"
        certificate ( generateSelfSigned ) "generateSelfSigned"
        startTlsEnabled ( true | false ) "false"
        secureReplication ( true | false ) "false" >
  <!ELEMENT tuning (java?,databaseCachePercentage?,replicationPurgeDelay?)>
    <!ELEMENT java EMPTY>
    <!ATTLIST java
        xms NMTOKEN #IMPLIED
        xmx NMTOKEN #IMPLIED
        xxNewSize NMTOKEN #IMPLIED
        xxMaxNewSize NMTOKEN #IMPLIED
        xxSurvivorRatio NMTOKEN #IMPLIED
        xxPermSize NMTOKEN #IMPLIED
        xxMaxPermSize NMTOKEN #IMPLIED
        xxUseConcMarkSweepGC NMTOKEN #IMPLIED>
    <!ELEMENT databaseCachePercentage (#PCDATA)>
    <!ELEMENT replicationPurgeDelay (#PCDATA)>
    <!ATTLIST replicationPurgeDelay unit ( s | m | h ) "s">


<!-- ========== SUFFIX NODE ========================= -->
<!ELEMENT suffix (topology,ldifFile?,tree?)> 
<!ATTLIST suffix 
    dn CDATA #REQUIRED>
  
  <!ELEMENT topology (element+)>
    <!ELEMENT element EMPTY>
    <!ATTLIST element
          instanceName NMTOKEN #REQUIRED
          initRule ( importLdif | totalUpdate ) "importLdif"
          instanceSourceName NMTOKEN #IMPLIED>
  
  <!ELEMENT ldifFile (#PCDATA)>
  
  <!ELEMENT tree (branch+,subordinateTemplate*)>
    <!ATTLIST tree nbOfEntries CDATA #REQUIRED>
    
    <!ELEMENT branch (branch*,subordinateTemplate*)>
    <!ATTLIST branch name CDATA #REQUIRED>
    
    <!ELEMENT subordinateTemplate EMPTY>
    <!ATTLIST subordinateTemplate
          type ( person | inetOrgPerson | organizationalPerson 
                 | inetOrgPerson_Jpeg_1MB | inetOrgPersonEXT_Jpeg_1MB) #REQUIRED
          percentage NMTOKEN #IMPLIED
          nb NMTOKEN #IMPLIED>


<!-- ========== CLIENT PHASES NODE ========================= -->
<!ELEMENT scheduler (duration,module+)>
  
  <!ELEMENT duration (#PCDATA)>
  <!ATTLIST duration 
    unit ( s | m | h | d ) "m">
  
  <!ELEMENT module (client+)>
  <!ATTLIST module
    name NMTOKEN #REQUIRED
    enabled ( true | false ) "true">
    
    <!ELEMENT client ANY>
    <!ATTLIST client
      id NMTOKEN #IMPLIED
      name ( searchLoad | modifyLoad | restartDs | sampleSearchLoad |
             verdictOpends | addDeleteLoad) "searchLoad"
      host NMTOKEN #IMPLIED
      start NMTOKEN #IMPLIED
      stop NMTOKEN #IMPLIED
      dependencyId CDATA #IMPLIED>
  
  
  <!ELEMENT serverInstance (#PCDATA)>
  <!ELEMENT baseDn (#PCDATA)>
  <!ELEMENT nbCnx (#PCDATA)>
  <!ELEMENT nbMaxOperations (#PCDATA)>
  <!ELEMENT attribute (#PCDATA)>
  <!ELEMENT authentication (#PCDATA)>
  <!ELEMENT certAlias (#PCDATA)>
  <!ELEMENT protocol (#PCDATA)>

=== clockard/OpenDJ/opends/tests/system-tests/scenario/4MMR/conf.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE systemTestConfiguration SYSTEM "../conf.dtd">
<!--
 ! CDDL HEADER START
 !
 ! The contents of this file are subject to the terms of the
 ! Common Development and Distribution License, Version 1.0 only
 ! (the "License").  You may not use this file except in compliance
 ! with the License.
 !
 ! You can obtain a copy of the license at
 ! trunk/opends/resource/legal-notices/OpenDS.LICENSE
 ! or https://OpenDS.dev.java.net/OpenDS.LICENSE.
 ! See the License for the specific language governing permissions
 ! and limitations under the License.
 !
 ! When distributing Covered Code, include this CDDL HEADER in each
 ! file and include the License file at
 ! trunk/opends/resource/legal-notices/OpenDS.LICENSE.  If applicable,
 ! add the following below this CDDL HEADER, with the fields enclosed
 ! by brackets "[]" replaced with your own identifying information:
 !      Portions Copyright [yyyy] [name of copyright owner]
 !
 ! CDDL HEADER END
 !
 !      Copyright 2008 Sun Microsystems, Inc.
 ! -->

<!--==================================================================-->
<!-- This conf.xml file is an example                                 -->
<!-- BEFORE running system-tests, you need to set up your environment -->
<!--==================================================================-->


<systemTestConfiguration>
  
  <!-- ================= Global Parameters ===================== -->
  <!-- =============  Should be the first node   =============== -->
  <globalParameters>
    <scenario>
      <name>4MMR</name>
      <description>
        4 Ldap Servers each connected to a single changelog server
      </description>
    </scenario>
    
    <opendsZip>/local/qa/build/OpenDS-1.0.0.zip</opendsZip>
    <!-- Example : <domain>france.sun.com</domain> -->
    <domain></domain>
  </globalParameters>
  
  
  <!-- ================= Instance ============================== -->
  <instance name="I1" product="opends" role="ldapServer">
    <host>localhost</host>
    <installDir>/local/qa/realtmp/systest/I1</installDir>
    <ports>
      <ldap>5021</ldap>
      <ldaps>5022</ldaps>
      <jmx>5023</jmx>
      <replicationServer>5025</replicationServer>
    </ports>
  </instance>
  
  <!-- ================= Instance ============================== -->
  <instance name="I2" product="opends" role="ldapServer">
    <host>localhost</host>
    <installDir>/local/qa/realtmp/systest/I2</installDir>
    <ports>
      <ldap>6021</ldap>
      <ldaps>6022</ldaps>
      <jmx>6023</jmx>
      <replicationServer>6025</replicationServer>
    </ports>
  </instance>
  
  <!-- ================= Instance ============================== -->
<!--  <instance name="I3" product="opends" role="ldapServer">
    <host>localhost</host>
    <installDir>NsEED_VALUE</installDir>
    <ports>
      <ldap>7021</ldap>
      <ldaps>7022</ldaps>
      <jmx>7023</jmx>
      <replicationServer>7025</replicationServer>
    </ports>
    <tuning>
      <java xms="2g" xmx="2g"
            xxNewSize="512m" xxMaxNewSize="512m"
            xxSurvivorRatio="6" xxPermSize="128m"
            xxMaxPermSize="128m" xxUseConcMarkSweepGC="true"/>
      <databaseCachePercentage>40</databaseCachePercentage>
      <replicationPurgeDelay unit="h">4</replicationPurgeDelay>
    </tuning>
  </instance>
-->  
  <!-- ================= Instance ============================== -->
<!--  <instance name="I4" product="opends" role="ldapServer">
    <host>localhost</host>
    <installDir>NsEED_VALUE</installDir>
    <ports>
      <ldap>8021</ldap>
      <ldaps>8022</ldaps>
      <jmx>8023</jmx>
      <replicationServer>8025</replicationServer>
    </ports>
    <tuning>
      <java xms="2g" xmx="2g"
            xxNewSize="512m" xxMaxNewSize="512m"
            xxSurvivorRatio="6" xxPermSize="128m"
            xxMaxPermSize="128m" xxUseConcMarkSweepGC="true"/>
      <databaseCachePercentage>40</databaseCachePercentage>
      <replicationPurgeDelay unit="h">4</replicationPurgeDelay>
    </tuning>
  </instance>
  -->
  <!-- ================= Suffix  ============================== -->
  <suffix dn="dc=com">
    
    <topology>
     	<element instanceName="I1" initRule="importLdif"/>
      <element instanceName="I2" initRule="totalUpdate"
               instanceSourceName="I1"/>
     <!-- <element instanceName="I3" initRule="totalUpdate"
               instanceSourceName="I1"/>
      <element instanceName="I4" initRule="totalUpdate"
               instanceSourceName="I1"/>-->
    </topology>
    
    <tree nbOfEntries="200">
      <branch name="ou=france,dc=com">
        <branch name="ou=QA Engineers,ou=france,dc=com">
          <subordinateTemplate type="inetOrgPerson" percentage="30"/>
        </branch>
        <branch name="ou=Accounting,ou=france,dc=com">
          <subordinateTemplate type="organizationalPerson" percentage="30"/>
        </branch>
        <branch name="ou=Managers,ou=france,dc=com">
          <subordinateTemplate type="person" nb="1"/>
        </branch>
        <branch name="ou=Engineers,ou=france,dc=com">
          <subordinateTemplate type="person" percentage="40"/>
        </branch>
      </branch>
    </tree>
    
  </suffix>
  
  
  <!-- ================= Scheduler  =========================== -->
  <!-- [1] duration must be more than 1 minute                  -->
  <!-- [2] dependencyId is a list of client id ie : 1,2         -->
  <!--     if using it, specify id attribute for each clients   -->
  <scheduler>
    <duration unit="m">2</duration> 
    <!-- 60h : 1% <-> 36 min , 10% <-> 6h -->
    
    
    <!-- ============================================================= -->
    <!--== Module 1 ==-->
    <module name="search" enabled="true">
      
      <client id="1" name="searchLoad" host="gahia" start="t0" stop="t100">
        <serverInstance>I1</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>2</nbCnx>
        <nbMaxOperations>2</nbMaxOperations>
        <attribute>sn</attribute>
      </client>
      <client id="2" name="modifyLoad" host="gahia" start="t10" stop="t90">
        <serverInstance>I1</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>2</nbCnx>
        <nbMaxOperations>2</nbMaxOperations>
        <attribute>sn</attribute>
      </client>
      <client id="8" name="restartDs" host="localhost" start="t70">
        <serverInstance>I1</serverInstance>
      </client>
    </module>
    
    
    <!--== Module 2 ==-->
    <module name="modify" enabled="false">
      
      <client id="3" name="modifyLoad" host="localhost" start="t20" stop="t50">
        <serverInstance>I1</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>20</nbCnx>
        <nbMaxOperations>20</nbMaxOperations>
        <attribute>sn</attribute>
      </client>
      
      <client id="4" name="searchLoad" host="localhost" start="t20" stop="t50">
        <serverInstance>I4</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>20</nbCnx>
        <nbMaxOperations>20</nbMaxOperations>
        <attribute>sn</attribute>
      </client>
      
    </module>
    
    
    <!--== Module 3 ==-->
    <module name="addAndDelete" enabled="true">
      
      <client id="6" name="addDeleteLoad" host="localhost" start="t60"
                                                           stop="t80">
        <serverInstance>I2</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>20</nbCnx>
      </client>
      
      <client id="7" name="restartDs" host="localhost" start="t70"
                                                       dependencyId="6">
        <serverInstance>I1</serverInstance>
      </client>
      
    </module>
    
    
  </scheduler>
  
</systemTestConfiguration>

=== clockard/OpenDJ/opends/tests/system-tests/scenario/sample2/conf.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE systemTestConfiguration SYSTEM "../conf.dtd">
<!--
 ! CDDL HEADER START
 !
 ! The contents of this file are subject to the terms of the
 ! Common Development and Distribution License, Version 1.0 only
 ! (the "License").  You may not use this file except in compliance
 ! with the License.
 !
 ! You can obtain a copy of the license at
 ! trunk/opends/resource/legal-notices/OpenDS.LICENSE
 ! or https://OpenDS.dev.java.net/OpenDS.LICENSE.
 ! See the License for the specific language governing permissions
 ! and limitations under the License.
 !
 ! When distributing Covered Code, include this CDDL HEADER in each
 ! file and include the License file at
 ! trunk/opends/resource/legal-notices/OpenDS.LICENSE.  If applicable,
 ! add the following below this CDDL HEADER, with the fields enclosed
 ! by brackets "[]" replaced with your own identifying information:
 !      Portions Copyright [yyyy] [name of copyright owner]
 !
 ! CDDL HEADER END
 !
 !      Copyright 2008 Sun Microsystems, Inc.
 ! -->

<!--==================================================================-->
<!-- This conf.xml file is an example                                 -->
<!-- BEFORE running system-tests, you need to set up your environment -->
<!--==================================================================-->


<systemTestConfiguration>
  
  <!-- ================= Global Parameters ===================== -->
  <!-- =============  Should be the first node   =============== -->
  <globalParameters>
    <scenario>
      <name>Sample2</name>
      <description>
        This is an example using pre/post configuration files
      </description>
    </scenario>
    
    <opendsName>OpenDS-1.0.0</opendsName>
    <opendsZip>NEED_VALUE</opendsZip>
    <domain>NEED_VALUE</domain>
    
  </globalParameters>
  
  
  <!-- ================= Instance ============================== -->
  <instance name="I1" product="opends">
    <host>localhost</host>
    <installDir>NEED_VALUE</installDir>
  </instance>
  
  <!-- ================= Instance ============================== -->
  <instance name="I2" product="opends">
    <host>localhost</host>
    <installDir>NEED_VALUE</installDir>
    <ports>
      <ldap>1234</ldap>
      <ldaps>1235</ldaps>
      <jmx>1236</jmx>
      <replicationServer>1237</replicationServer>
    </ports>
  </instance>
  
  
  <!-- ================= Suffix  ============================== -->
  <suffix dn="dc=com">
    
    <topology>
     	<element instanceName="I1" initRule="importLdif"/>
      <element instanceName="I2" initRule="totalUpdate"
               instanceSourceName="I1"/>
    </topology>
    
    <tree nbOfEntries="50">
      <branch name="ou=france,dc=com">
        <branch name="ou=QA Engineers,ou=france,dc=com">
          <subordinateTemplate type="inetOrgPerson" percentage="30"/>
        </branch>
        <branch name="ou=Accounting,ou=france,dc=com">
          <subordinateTemplate type="organizationalPerson" percentage="30"/>
        </branch>
        <branch name="ou=Managers,ou=france,dc=com">
          <subordinateTemplate type="person" nb="1"/>
        </branch>
        <branch name="ou=Engineers,ou=france,dc=com">
          <subordinateTemplate type="person" percentage="40"/>
        </branch>
      </branch>
    </tree>
    
  </suffix>
  
  
  <!-- ================= Scheduler  =========================== -->
  <!-- [1] duration must be more than 1 minute                  -->
  <!-- [2] dependencyId is a list of client id ie : 1,2         -->
  <!--     if using it, specify id attribute for each clients   -->
  <scheduler>
    <duration unit="m">4</duration>
    
    <!--== Module 1 ==-->
    <module name="search" enabled="true">
    
      <client id="1" name="searchLoad" host="localhost" start="t30"
                                                         stop="t60">
        <serverInstance>I1</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>5</nbCnx>
        <nbMaxSearch>5</nbMaxSearch>
        <attribute>sn</attribute>
      </client>
      
      <client id="2" name="searchLoad" host="localhost" start="t0"
                                                         stop="t50">
        <serverInstance>I2</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>5</nbCnx>
        <nbMaxSearch>5</nbMaxSearch>
        <attribute>sn</attribute>
      </client>
      
    </module>
    
    <!--== Module 2 ==-->
    <module name="restart_and_modify" enabled="true">
      
      <client id="3" name="restartDs" host="localhost" start="t50"
                                                        dependencyId="1">
        <serverInstance>I2</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>5</nbCnx>
        <nbMaxSearch>5</nbMaxSearch>
        <attribute>sn</attribute>
      </client>
      
      <client id="4" name="modifyLoad" host="localhost" start="t60"
                                                         stop="t100">
        <serverInstance>I1</serverInstance>
        <baseDn>dc=com</baseDn>
        <nbCnx>5</nbCnx>
        <nbMaxSearch>5</nbMaxSearch>
        <attribute>sn</attribute>
      </client>
    </module>
    
    
  </scheduler>
  
</systemTestConfiguration>
